version: '3'

services:
  db:
    image: mariadb
    volumes:
      - /root/3dg/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
  app:
    build: .
    # image: php:fpm-alpine
    volumes:
      - /root/3dg/app:/var/www/html
    command: sh -c "chown -R www-data:www-data /var/www/html && docker-php-entrypoint php-fpm"
    depends_on:
      - db
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
        - /root/3dg/app/app.conf:/etc/nginx/conf.d/app.conf
        - /root/3dg/app:/appstatic
    depends_on:
      - app
